import type { User } from "@supabase/supabase-js"

/**
 * Local cache for the "Where you left off" one-sentence recap (see
 * src/lib/translate/page-recap.ts and where-you-left-off-modal.tsx).
 *
 * The recap is generated by a single Gemini Flash Lite call made once, when the reader
 * *leaves* a book (see the leave-triggered effect in App.tsx) -- never on reopen. This cache
 * is what makes that possible: it's written right after that one call succeeds, and read
 * synchronously (no network) the next time the same book is opened, so a reopen never pays
 * for a second call. Scoped by user id (falls back to a shared "guest" bucket pre-login),
 * same convention as reading-progress-storage.ts.
 *
 * Like reading-progress-storage.ts, this is a cache and not the only copy: a signed-in
 * reader's recap is also written to their `reading_progress` row (the `recap_*` columns --
 * see reading-progress-sync.ts and supabase/migrations/0024_reading_progress_recap.sql) and
 * pulled back down into here on the next session (`mergeCloudRecaps`), so the recap travels
 * with the position instead of being stranded in whichever browser generated it.
 */
export const READING_RECAP_STORAGE_KEY = "lector-reading-recap"

/** Safety cap so a long history of read books can't grow the stored blob unbounded. */
const MAX_TRACKED_ITEMS_PER_USER = 300

interface RecapEntry {
  summary: string
  /**
   * 0-based index of the page this summary is *of* -- the page immediately before the resume
   * point at the moment it was generated, not the resume page itself. Only a reliable staleness
   * check on the *same device*: a page index is specific to whichever device's own page-split
   * produced it (e.g. mobile and desktop paginate the same book differently -- see `isMobile` in
   * App.tsx), so this alone would make the cache look stale every time reading continues on a
   * different device than the one that generated it. See `forSentenceIndex` for the
   * device-independent check; this field is only the fallback for entries that predate it.
   */
  forPageIndex: number
  /**
   * Sentence-index anchor (see computePageStartSentenceIndices) for the same page as
   * `forPageIndex`, at the moment this was generated -- device-independent, unlike a raw page
   * index, so this is what makes the cached recap still match after reading continues on a
   * *different* device (e.g. desktop then mobile) whose own page-split puts that same spot at a
   * different page index. Undefined when no anchor was available when this was generated (e.g.
   * the whole text segmented into a single "sentence" -- see the pageStartSentenceIndicesRef
   * comment in App.tsx); `forPageIndex` is the only check available then.
   */
  forSentenceIndex?: number
  updatedAt: number
}

type UserRecapMap = Record<string, RecapEntry>
type AllRecap = Record<string, UserRecapMap>

function scopeKeyFor(user: User | null): string {
  return user?.id ?? "guest"
}

function readAll(): AllRecap {
  if (typeof window === "undefined") return {}
  try {
    const raw = localStorage.getItem(READING_RECAP_STORAGE_KEY)
    if (!raw) return {}
    const parsed: unknown = JSON.parse(raw)
    return parsed && typeof parsed === "object" ? (parsed as AllRecap) : {}
  } catch {
    return {}
  }
}

function writeAll(data: AllRecap): void {
  try {
    localStorage.setItem(READING_RECAP_STORAGE_KEY, JSON.stringify(data))
  } catch {
    /* quota / private mode */
  }
}

/**
 * The cached recap for `contentId`, but only if it's still for the page right before wherever
 * the reader is resuming to now. Preferentially matched by `expectedPreviousPageSentenceIndex`
 * (device-independent -- see `forSentenceIndex` above) when both the cached entry and this call
 * have one; only falls back to the raw `expectedPreviousPageIndex` match when either side lacks
 * a sentence anchor (older cached entries, or the rare text that segmented into a single
 * sentence). This is what lets a recap generated when the reader left off on one device (e.g.
 * desktop) still show up when they resume on another (e.g. mobile), whose own page-split would
 * otherwise put that same spot at a different raw page index and make the cache look stale.
 * Returns null for "no cached recap" and for "cached, but stale" alike; either way the caller
 * (the modal) just falls back to the free verbatim excerpt instead of an LLM summary.
 */
export function getCachedPageRecap(
  user: User | null,
  contentId: string,
  expectedPreviousPageIndex: number,
  expectedPreviousPageSentenceIndex?: number | null,
): string | null {
  const scoped = readAll()[scopeKeyFor(user)]
  const entry = scoped?.[contentId]
  if (!entry) return null
  const matches =
    entry.forSentenceIndex != null && expectedPreviousPageSentenceIndex != null
      ? entry.forSentenceIndex === expectedPreviousPageSentenceIndex
      : entry.forPageIndex === expectedPreviousPageIndex
  if (!matches) return null
  return entry.summary || null
}

/** Records a freshly-generated recap for `contentId`, of the page at `forPageIndex`. */
export function setCachedPageRecap(
  user: User | null,
  contentId: string,
  forPageIndex: number,
  summary: string,
  forSentenceIndex?: number | null,
): void {
  const trimmed = summary.trim()
  if (!trimmed) return
  const all = readAll()
  const scope = scopeKeyFor(user)
  const scoped = { ...(all[scope] ?? {}) }
  scoped[contentId] = {
    summary: trimmed,
    forPageIndex,
    ...(forSentenceIndex != null ? { forSentenceIndex } : {}),
    updatedAt: Date.now(),
  }

  const entries = Object.entries(scoped)
  if (entries.length > MAX_TRACKED_ITEMS_PER_USER) {
    // Drop the oldest first -- keeps the most recently-read items.
    entries.sort((a, b) => a[1].updatedAt - b[1].updatedAt)
    const overflow = entries.length - MAX_TRACKED_ITEMS_PER_USER
    for (let i = 0; i < overflow; i++) delete scoped[entries[i]![0]]
  }

  all[scope] = scoped
  writeAll(all)
}

/** One `reading_progress` row's recap half, as pulled from Supabase -- see reading-progress-sync.ts. */
export interface CloudRecapRow {
  contentId: string
  summary: string
  /** Null for rows whose recap predates / lacks a raw page index. */
  forPageIndex: number | null
  /** Null when the recap was generated without a sentence anchor -- see `forSentenceIndex`. */
  forSentenceIndex: number | null
  /** `recap_updated_at` (not the row's `updated_at`, which a plain page turn bumps). */
  updatedAt: number
}

/**
 * Merges recaps pulled from Supabase into this user's local cache, last-write-wins by
 * `updatedAt` -- same shape and rules as `mergeCloudProgress` in reading-progress-storage.ts.
 * A local entry that's newer than (or as new as) the cloud copy always wins, so a recap this
 * browser generated moments ago can't be replaced by an older one from another device.
 *
 * This is what makes the recap survive a new browser/session: the modal's cache read
 * (`getCachedPageRecap`) still happens synchronously with no network call, it just now has
 * something to find on a device that never generated the recap itself.
 */
export function mergeCloudRecaps(user: User | null, rows: CloudRecapRow[]): void {
  if (rows.length === 0) return
  const all = readAll()
  const scope = scopeKeyFor(user)
  const scoped = { ...(all[scope] ?? {}) }
  let changed = false
  for (const row of rows) {
    const summary = row.summary.trim()
    if (!summary || !Number.isFinite(row.updatedAt)) continue
    const existing = scoped[row.contentId]
    if (existing && existing.updatedAt >= row.updatedAt) continue
    scoped[row.contentId] = {
      summary,
      // A cloud recap with no page index of its own can only ever be matched by its sentence
      // anchor; -1 is a page index no lookup ever asks for, so it simply never false-matches.
      forPageIndex: row.forPageIndex ?? -1,
      ...(row.forSentenceIndex != null ? { forSentenceIndex: row.forSentenceIndex } : {}),
      updatedAt: row.updatedAt,
    }
    changed = true
  }
  if (!changed) return
  all[scope] = scoped
  writeAll(all)
}
