import { cn } from "@/lib/utils"

/**
 * Geometry of the brand mark, kept here so the React component and the
 * standalone assets in /public (lexa-lens-mark.svg, favicon.svg) stay in sync.
 *
 * RING — drawn as a filled shape, not a stroked circle: a true circle minus an
 * ellipse that is narrower than it is tall and tipped 14°. That leaves the ring
 * thick at the sides and thin at the top/bottom, the same modulated stroke a
 * high-contrast serif "O" has, so it sits next to the Fraunces wordmark instead
 * of looking like a UI icon dropped beside it.
 *
 * TILDE — the eñe/tilde is the one diacritic no one reads as another language,
 * which is the whole point: the mark it replaces (a generic translate glyph)
 * put a Chinese character on a Spanish product. Also drawn as a filled outline
 * rather than a stroke, so it tapers to a fine point at each end like a pen
 * stroke. Generated by offsetting a two-segment spline; hand-editing the point
 * list will only make it lumpy — redraw it instead.
 */
const RING_PATH =
  "M3 16a13 13 0 1 0 26 0a13 13 0 1 0-26 0Z" +
  "M7.27 18.18A9 10.55 -14 1 0 24.73 13.82A9 10.55 -14 1 0 7.27 18.18Z"

const TILDE_PATH =
  "M9.53 17.66L10 17.37L10.33 17.07L10.64 16.8L10.94 16.56L11.22 16.36L11.5 16.19L11.77 16.05L12.02 15.95L12.27 15.87L12.5 15.82L12.73 15.79L12.93 15.77L13.13 15.78L13.32 15.8L13.5 15.84L13.67 15.89L13.83 15.96L13.99 16.03L14.15 16.12L14.31 16.23L14.46 16.35L14.61 16.49L14.77 16.64L14.92 16.82L15.23 17.19L15.57 17.52L15.94 17.82L16.33 18.07L16.73 18.28L17.16 18.45L17.59 18.58L18.03 18.66L18.48 18.69L18.92 18.67L19.36 18.61L19.78 18.5L20.2 18.35L20.6 18.16L20.97 17.92L21.33 17.65L21.66 17.35L21.96 17.01L22.24 16.64L22.48 16.23L22.69 15.8L22.87 15.34L22.98 14.84L22.93 14.26L22.67 14.14L22.2 14.43L21.87 14.73L21.56 15L21.26 15.24L20.98 15.44L20.7 15.61L20.43 15.75L20.18 15.85L19.93 15.93L19.7 15.98L19.47 16.01L19.27 16.03L19.07 16.02L18.88 16L18.7 15.96L18.53 15.91L18.37 15.84L18.21 15.77L18.05 15.68L17.89 15.57L17.74 15.45L17.59 15.31L17.43 15.16L17.28 14.98L16.97 14.61L16.63 14.28L16.26 13.98L15.87 13.73L15.47 13.52L15.04 13.35L14.61 13.22L14.17 13.14L13.72 13.11L13.28 13.13L12.84 13.19L12.42 13.3L12 13.45L11.6 13.64L11.23 13.88L10.87 14.15L10.54 14.45L10.24 14.79L9.96 15.16L9.72 15.57L9.51 16L9.33 16.46L9.22 16.96L9.27 17.54Z"

type LexaLensMarkProps = {
  className?: string
  /**
   * "outline" — ring + tilde, for the header/footer lockup.
   * "solid"   — knocked out of a filled disc, for tiny or busy backgrounds
   *             (favicon, app icon). Holds together below ~20px where the
   *             ring's thin sections start to disappear.
   */
  variant?: "outline" | "solid"
}

export function LexaLensMark({ className, variant = "outline" }: LexaLensMarkProps) {
  return (
    <svg
      viewBox="0 0 32 32"
      className={cn("shrink-0", className)}
      aria-hidden
      focusable="false"
    >
      {variant === "solid" ? (
        <>
          <circle cx="16" cy="16" r="13.6" className="fill-[#c97a5a] dark:fill-[#d4a896]" />
          <path d={TILDE_PATH} className="fill-[#f7f3ee] dark:fill-[#1a1a1a]" />
        </>
      ) : (
        <>
          <path d={RING_PATH} fillRule="evenodd" className="fill-[#3a332e] dark:fill-[#e8dfd4]" />
          <path d={TILDE_PATH} className="fill-[#c97a5a] dark:fill-[#d4a896]" />
        </>
      )}
    </svg>
  )
}
