-- =============================================================================
-- Migration: 0001_subscription_management
-- Description: Subscription management — user plans, usage tracking, invoices.
--
-- Tables created:
--   user_subscriptions  — one active record per user; soft-deleted on cancel
--   usage_records       — aggregated counters per billing period per user
--   billing_invoices    — local mirror of Stripe invoice objects for audit
--
-- Conventions:
--   • All PKs are UUIDs generated by gen_random_uuid().
--   • Every table has created_at / updated_at (updated_at via trigger).
--   • Soft delete: archived_at IS NOT NULL means the row is archived.
--   • Active views exclude archived rows for easy app-side querying.
--   • RLS is enabled on every table; policies follow the pattern:
--       users can only read/write their own rows.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 0. Extensions
-- ---------------------------------------------------------------------------
create extension if not exists "pgcrypto";   -- gen_random_uuid() on older PG
create extension if not exists "moddatetime"; -- auto-update updated_at

-- ---------------------------------------------------------------------------
-- 1. Enum types
-- ---------------------------------------------------------------------------

-- Mirrors the TierId union in src/lib/tiers.ts — keep in sync.
create type public.plan_id as enum (
  'free',
  'pro',
  'unlimited'
);

create type public.billing_interval as enum (
  'monthly',
  'annual'
);

-- Mirrors Stripe subscription statuses plus our own 'paused'.
create type public.subscription_status as enum (
  'trialing',
  'active',
  'past_due',
  'paused',
  'canceled',
  'incomplete',
  'incomplete_expired',
  'unpaid'
);

create type public.invoice_status as enum (
  'draft',
  'open',
  'paid',
  'void',
  'uncollectible'
);

-- ---------------------------------------------------------------------------
-- 2. updated_at trigger function (shared)
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- 3. user_subscriptions
--    One canonical row per user. When a subscription is canceled it is NOT
--    deleted — canceled_at and (eventually) archived_at are set instead.
--    A new subscription for the same user creates a new row; the old one
--    is archived so billing history is preserved.
-- ---------------------------------------------------------------------------
create table public.user_subscriptions (
  -- Identity
  id                      uuid primary key default gen_random_uuid(),
  user_id                 uuid not null references auth.users (id) on delete cascade,

  -- Plan
  plan_id                 public.plan_id        not null default 'free',
  billing_interval        public.billing_interval not null default 'monthly',

  -- Stripe references
  stripe_customer_id      text,
  stripe_subscription_id  text unique,          -- null on free tier

  -- Status
  status                  public.subscription_status not null default 'active',

  -- Billing period
  current_period_start    timestamptz,
  current_period_end      timestamptz,          -- aka next_billing_date
  trial_start             timestamptz,
  trial_end               timestamptz,

  -- Cancellation (soft delete)
  cancel_at_period_end    boolean not null default false,
                                                -- true = Stripe will cancel at period end
  canceled_at             timestamptz,          -- when cancellation was requested
  cancellation_reason     text,                 -- optional free-text or Stripe feedback code

  -- Archival (hard soft-delete — keeps the row but removes from active queries)
  archived_at             timestamptz,          -- set when a new subscription supersedes this one

  -- Audit
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),

  -- Constraints
  constraint chk_period_order
    check (current_period_start is null or current_period_end is null
           or current_period_end > current_period_start),
  constraint chk_trial_order
    check (trial_start is null or trial_end is null
           or trial_end > trial_start),
  constraint chk_archived_after_canceled
    check (archived_at is null or canceled_at is null
           or archived_at >= canceled_at)
);

-- Indexes
create index idx_user_subscriptions_user_id
  on public.user_subscriptions (user_id);

create index idx_user_subscriptions_status
  on public.user_subscriptions (status)
  where archived_at is null;                    -- partial: skip archived rows

create index idx_user_subscriptions_stripe_customer
  on public.user_subscriptions (stripe_customer_id)
  where stripe_customer_id is not null;

create index idx_user_subscriptions_period_end
  on public.user_subscriptions (current_period_end)
  where archived_at is null;                    -- for renewal/expiry jobs

-- Active subscription per user (the one the app actually enforces)
create unique index idx_user_subscriptions_one_active_per_user
  on public.user_subscriptions (user_id)
  where archived_at is null;                    -- only one non-archived row per user

-- updated_at trigger
create trigger trg_user_subscriptions_updated_at
  before update on public.user_subscriptions
  for each row execute procedure public.set_updated_at();

-- RLS
alter table public.user_subscriptions enable row level security;

create policy "Users can read their own subscription"
  on public.user_subscriptions for select
  using (auth.uid() = user_id);

create policy "Service role has full access to subscriptions"
  on public.user_subscriptions for all
  using (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- 3a. Active-subscriptions view (convenience — excludes archived rows)
-- ---------------------------------------------------------------------------
create view public.active_subscriptions as
  select *
  from public.user_subscriptions
  where archived_at is null;

comment on view public.active_subscriptions
  is 'Non-archived subscriptions only. Use this view for all application queries.';

-- ---------------------------------------------------------------------------
-- 4. usage_records
--    One row per user per billing period. Counters are incremented in-place
--    by the backend as the user consumes quota. A new row is inserted at the
--    start of each billing period (or on first use if none exists yet).
-- ---------------------------------------------------------------------------
create table public.usage_records (
  -- Identity
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references auth.users (id) on delete cascade,
  subscription_id     uuid not null references public.user_subscriptions (id) on delete cascade,

  -- Billing period this record covers
  period_start        timestamptz not null,
  period_end          timestamptz not null,

  -- Counters (all default 0; incremented atomically via UPDATE ... SET x = x + n)
  texts_processed     integer  not null default 0 check (texts_processed     >= 0),
  chunks_returned     integer  not null default 0 check (chunks_returned     >= 0),
  pages_processed     integer  not null default 0 check (pages_processed     >= 0),
  chars_processed     bigint   not null default 0 check (chars_processed     >= 0),
  api_calls           integer  not null default 0 check (api_calls           >= 0),
  voice_requests      integer  not null default 0 check (voice_requests      >= 0),

  -- Audit
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  constraint chk_usage_period_order
    check (period_end > period_start)
);

-- Indexes
create index idx_usage_records_user_id
  on public.usage_records (user_id);

create index idx_usage_records_subscription_id
  on public.usage_records (subscription_id);

-- Fast lookup of the current period's record for a user
create index idx_usage_records_user_period
  on public.usage_records (user_id, period_start desc);

-- Enforce one record per subscription period (prevents accidental double-insert)
create unique index idx_usage_records_unique_period
  on public.usage_records (subscription_id, period_start);

-- updated_at trigger
create trigger trg_usage_records_updated_at
  before update on public.usage_records
  for each row execute procedure public.set_updated_at();

-- RLS
alter table public.usage_records enable row level security;

create policy "Users can read their own usage"
  on public.usage_records for select
  using (auth.uid() = user_id);

create policy "Service role has full access to usage"
  on public.usage_records for all
  using (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- 5. billing_invoices
--    Local mirror of Stripe Invoice objects. Written by your webhook handler
--    on invoice.created / invoice.updated / invoice.paid / invoice.payment_failed.
--    Never mutated by the client — service_role only for writes.
-- ---------------------------------------------------------------------------
create table public.billing_invoices (
  -- Identity
  id                          uuid primary key default gen_random_uuid(),
  user_id                     uuid not null references auth.users (id) on delete cascade,
  subscription_id             uuid references public.user_subscriptions (id) on delete set null,

  -- Stripe references
  stripe_invoice_id           text not null unique,
  stripe_charge_id            text,
  stripe_payment_intent_id    text,

  -- Amount
  amount_due_cents            integer not null check (amount_due_cents >= 0),
  amount_paid_cents           integer not null default 0 check (amount_paid_cents >= 0),
  amount_remaining_cents      integer not null default 0 check (amount_remaining_cents >= 0),
  currency                    char(3) not null default 'usd',

  -- Status
  status                      public.invoice_status not null default 'draft',

  -- Stripe billing metadata
  billing_reason              text,
                                -- 'subscription_create' | 'subscription_cycle' |
                                -- 'subscription_update' | 'manual' | etc.
  collection_method           text,
                                -- 'charge_automatically' | 'send_invoice'

  -- Dates
  invoice_date                timestamptz,      -- Stripe's created timestamp
  due_date                    timestamptz,
  paid_at                     timestamptz,
  voided_at                   timestamptz,

  -- Billing period the invoice covers
  period_start                timestamptz,
  period_end                  timestamptz,

  -- PDF / portal links (refreshed from Stripe as needed)
  invoice_pdf_url             text,
  hosted_invoice_url          text,

  -- Raw Stripe payload for full auditability (never queried — stored for debugging)
  stripe_payload              jsonb,

  -- Audit
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),

  constraint chk_invoice_period_order
    check (period_start is null or period_end is null
           or period_end > period_start)
);

-- Indexes
create index idx_billing_invoices_user_id
  on public.billing_invoices (user_id);

create index idx_billing_invoices_subscription_id
  on public.billing_invoices (subscription_id);

create index idx_billing_invoices_status
  on public.billing_invoices (status);

-- Webhook idempotency: look up by Stripe invoice ID instantly
create index idx_billing_invoices_stripe_invoice_id
  on public.billing_invoices (stripe_invoice_id);

-- Chronological invoice list per user
create index idx_billing_invoices_user_date
  on public.billing_invoices (user_id, invoice_date desc);

-- updated_at trigger
create trigger trg_billing_invoices_updated_at
  before update on public.billing_invoices
  for each row execute procedure public.set_updated_at();

-- RLS
alter table public.billing_invoices enable row level security;

create policy "Users can read their own invoices"
  on public.billing_invoices for select
  using (auth.uid() = user_id);

create policy "Service role has full access to invoices"
  on public.billing_invoices for all
  using (auth.role() = 'service_role');

-- ---------------------------------------------------------------------------
-- 6. Table / column comments
-- ---------------------------------------------------------------------------
comment on table public.user_subscriptions is
  'One non-archived row per user representing their current plan. Canceled subscriptions are soft-deleted via canceled_at; superseded subscriptions are archived via archived_at.';

comment on column public.user_subscriptions.cancel_at_period_end is
  'Mirrors the Stripe flag. User retains access until current_period_end, then status flips to canceled.';

comment on column public.user_subscriptions.archived_at is
  'Set when a new subscription supersedes this one. Archived rows are excluded from active_subscriptions view and from the one-active-per-user unique index.';

comment on table public.usage_records is
  'Aggregated usage counters per user per billing period. One row per (subscription_id, period_start). Increment counters atomically: UPDATE usage_records SET texts_processed = texts_processed + 1 WHERE ...';

comment on table public.billing_invoices is
  'Local mirror of Stripe Invoice objects. Written exclusively by the Stripe webhook handler (service_role). Client has read-only access.';

comment on column public.billing_invoices.stripe_payload is
  'Full raw Stripe Invoice JSON. Not indexed or used by application logic — retained for debugging and compliance audits only.';
